name: Slack Notify

inputs:
  webhook_url:
    required: true
  status:
    required: true
runs:
  using: composite
  steps:
    - name: Send Slack
      shell: bash
      env:
        WEBHOOK_URL: ${{ inputs.webhook_url }}
      run: |
        payload=$(cat <<EOF
        {
          "text": ステータス: success",
          attachments: [{
            color: good,
            fields: [
              {title: "タイトル", value: "【通常】本番リリース", short: true},
              {title: "リポジトリ", value: "org/repos", short: true},
              {title: "ブランチ/タグ", value: "1.0.0", short: true},
              {title: "実行者", value: "masatake", short: true},
              {title: "ワークフローURL", value: "<\(https://xxx)|(https://xxx)>", short: true}
            ]
          }]
        }
        EOF
        )

        curl \
          -X POST \
          -H 'Content-type: application/json' \
          --data "$payload" \
          "$WEBHOOK_URL"





