name: Reusable Java CI

on:
  workflow_call:

jobs:
  webhook_test:
    runs-on: ubuntu-latest

    steps:
      - name: Webhook Test
        uses: masatake0511/pipeline-template/.github/actions/webhook@main
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

